### ISSUE TITLE
float formatting when writing STAR files

### ISSUE THREAD

**Issue by bingwang14** [alisterburt/starfile#1]
Hi,

Thank you for sharing the module. But I met a problem when using it. Here is the specific issue.
When I write a pandas dataframe to a star file with starfile.new() function, it changes the decimal place for all data. The data in dataframe is 6 decimal places(%0.6f), while in the output star file, it is 5 decimal places(%0.5f). For example, 3374.201417 is changed to 3374.20142. Is there any way to avoid that?

Thanks,
Bing

**Comment by alisterburt** [comment]
Hi Bing,

Thanks for letting me know. I've uploaded an updated version (0.1.3) to PyPi which will allow you to pass keyword arguments when writing new star files. Actually writing the loop style data blocks is delegated to pandas DataFrame.to_csv(), any keyword arguments you pass to starfile.new() will now be passed through to the DataFrame.to_csv() call. Keyword arguments for that are listed at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

I've left the default at %.5f (to avoid large files when doing mathematical operations on euler angles for instance), to achieve what you want you could now write the following

`starfile.new(df, 'test.star', float_format='%.6f')`

Hope that helps, let me know if you feel like this default behaviour isn't correct

**Comment by bingwang14** [comment]
Hi,

Thank you so much. It works well.

Regards,
Bing
________________________________
