### ISSUE TITLE
Optics block reformatted 

### ISSUE THREAD

**Issue by ryanfeathers** [alisterburt/starfile#25]
Hi @alisterburt 

Thanks for making such a useful tool! 

I ran into one issue with unintentional reformatting of the optics table and I'm wondering if this is a bug or if my script is incorrect.

When I use starfile to read a relion3 style file, manipulate the particle table, then write the edited file, the optics table changes from

input:
```
data_optics

loop_
_rlnVoltage #1 
_rlnSphericalAberration #2 
_rlnAmplitudeContrast #3 
_rlnOpticsGroup #4 
_rlnImageSize #5 
_rlnImagePixelSize #6 
_rlnImageDimensionality #7 
200.000000 2.700000 0.100000 6 100 2.999998 2
```
output:
```
data_optics

_rlnVoltage			200.0
_rlnSphericalAberration			2.7
_rlnAmplitudeContrast			0.1
_rlnOpticsGroup			6
_rlnImageSize			100
_rlnImagePixelSize			2.999998
_rlnImageDimensionality			2

```
Do you have any suggestions?

**Comment by alisterburt** [comment]
Hi @ryanfeathers - you hit the limits of my simple data model! congratulations 😆 

I wanted everything to be dataframes and a (1, N) row is a bit ambiguous, should it be written as a simple block or a loop block? I decided to default to simple block and @robertbuecker added a keyword argument `force_loop=True` to `starfile.write()` in #24 - does this solve your issue?

**Comment by ryanfeathers** [comment]
Yes that's perfect! Thank you 😄

**Comment by Guillawme** [comment]
Should writing out a loop be the default then? It seems like correctly writing out the optics table should be the default. But I don't know what else would break if this became the default behavior.

**Comment by alisterburt** [comment]
It's definitely something we could do - my experience with RELION is that its internal model parses loops and simple blocks into the same structure so this hasn't caused me any issues but please correct me if I'm wrong, I'm no power user

I'm not sure what's best so would definitely consider a PR changing the default :)

**Comment by ryanfeathers** [comment]
this format is interpreted by relion as an empty optics table which produces the slightly confusing error: `optics group "" does not exist in micrograph star file.` 

it's an easy fix if you know to manually edit the optics table or if you know to use the force_block option! 😅 I agree it seems like it makes sense to force block as default but not a big deal if there's good reason to keep it as is. 
```
data_optics

_rlnVoltage			200.0
_rlnSphericalAberration			2.7
_rlnAmplitudeContrast			0.1
_rlnOpticsGroup			6
_rlnImageSize			100
_rlnImagePixelSize			2.999998
_rlnImageDimensionality			2
```

**Comment by Guillawme** [comment]
It is an easy fix only if 1) you know where to look for the problem (the error message about optics groups is indeed confusing) and 2) your optics table is small enough to fix manually. I have been dealing with as many as 42 entries in the optics table: this is still fixable semi-manually (interactive search and replace) but already very tedious and error-prone.

Note that this is not at all a complaint about `starfile`, I needed to edit my large optics table for a different reason. I simply thought I should point out that the optics table is not always limited to a couple entries, therefore having it written out correctly by default seems reasonable. If it is simply a matter of changing a keyword argument's default value, this should be doable with my limited coding skills, so I will try to figure it out and submit a PR when time allows.

**Comment by ryanfeathers** [comment]
Sorry to revive this but I'm still getting optics tables that look like force_loop=False but now if I try using force_loop=True I get an unexpected argument error. 

Should the writer.py force_loop value also be changed in line 22?

https://github.com/alisterburt/starfile/blob/0fa8e54224348eccf588792744c310ad588f0d5d/starfile/writer.py#L22

**Comment by alisterburt** [comment]
@ryanfeathers uh oh, could you provide a minimal example so that I can look into it?

**Comment by alisterburt** [comment]
the default value shouldn't need changing there as the default in the function is passed to `StarWriter` here
https://github.com/Guillawme/starfile/blob/f5f80f360891ab50eda9d12276d9dbe758071de5/starfile/functions.py#L31-L42

**Comment by ryanfeathers** [comment]
@alisterburt sure, here is a sample input and output. I've also included the script that I'm using with starfile to produce this result.

https://drive.google.com/drive/folders/1fv-4lJ2t_uuvIjNJzWkfT7IHzFyTgdYo?usp=sharing

**Comment by alisterburt** [comment]
Hi @ryanfeathers - it looks like you're using an older version of the package (`0.4.5`) from before `force_loop` was added, this is probably why you're getting errors! Could you try upgrading? Hopefully this will solve your issue 🙂 

`pip install --upgrade starfile`

**Comment by ryanfeathers** [comment]
@alisterburt well now I'm embarrassed because that does seem to be the problem but I can't figure out why 0.4.5 is the latest version I can install with pip install starfile or pip install --upgrade starfile 🤨

**Comment by alisterburt** [comment]
No need to be embarrassed - these things happen! Are you on python 3.6? I think I moved to 3.7+ with 0.4.6 

In general, I like the ideas in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) 🙂
