### ISSUE TITLE
access specific dataframes using names rather than list index

### ISSUE THREAD

**Issue by alisterburt** [alisterburt/starfile#4]

**Comment by robertbuecker** [comment]
Hi,
I'm totally in favor of this! In fact, in my codes I'm using this wrapper to keep the dataframes in an `OrderedDict` (as a plain `dict` might mess up the ordering of tables in the star file), which does the trick quite nicely:
```
import starfile
from collections import OrderedDict

def read_star(fn: str) -> OrderedDict: 
    return OrderedDict([(df.name, df) for df in starfile.read(fn)])

def write_star(tables: OrderedDict, fn: str):
    for lbl, tbl in tables.items():
        tbl.name = lbl
    starfile.new(list(tables.values()), fn)
```
Having a similar function directly built in would of course be much more elegant.
And thanks for the excellent package, it's really of huge value.
Robert

**Comment by alisterburt** [comment]
Hey Robert,

Really appreciate the feedback and suggestion, thank you, I'm glad you find it useful! :)

This is a great way to achieve what we want, the ordering and possibility of breaking existing scripts were my main concerns, what are your feelings on trying to maintain the list-like indexing? Is it necessary?

Possible issue:
- we would need to add some mechanism to catch multiple data blocks with identical names (or without a name, which I've come across in some older files)

This is on my to do list for sure but if you want to sink some time into it then a PR is of course welcome! 
I'm going to add a couple of other issues for a few other things I've got in mind now

**Comment by robertbuecker** [comment]
Hey,
unnamed data blocks could e.g. be handled with a counting integer key instead of a string, I see no issue with mixing key types. However, I don't really see a good option for non-unique names, that's a good point indeed. A workaround could be to represent the tables as lists of tuples `[('optics', opt_tbl), ('particles', prt_tbl), ('particles', another_prt_tbl)]`, which directly converts into a `dict` or `OrderedDict` if you're sure the keys are unique.
For me personally list-like indexing is of no big use, but I guess it would be too brutal a compatibility break... one could add it as an option for the functions, and as properties in the class though. I can look into it, maybe some time next week.

**Comment by alisterburt** [comment]
I agree on the key types, not so sure on the list of tuples as anything but an intermediate representation 
how about this...

- data blocks are parsed one by one, an integer counter starts which increments with each new block
- in the final ordered dict, keys are `df.name` if this is neither empty nor an existing key, else they are the integer key

Good to hear your thoughts on indexing! Interested to see/chat about anything you come up with.

**Comment by alisterburt** [comment]
started work on this in alisterburt/starfile@05ac4282854daeb18bb320456be5b7d8f0e82c02 along with a big refactor, pre-warning that this will include quite big changes related to #6 so any PR may prove difficult

**Comment by Guillawme** [comment]
> For me personally list-like indexing is of no big use, but I guess it would be too brutal a compatibility break... one could add it as an option for the functions, and as properties in the class though. I can look into it, maybe some time next week.

Assuming this library follows [Semantic Versioning](https://semver.org/), an acceptable solution would be to apply this "brutal compatibility break" with an increment in major version number. This is exactly the kind of thing the major version number is meant to convey to users. Then it would not require complicating the interface with an option to switch functions' behavior.

**Comment by alisterburt** [comment]
I completely agree, this is the direction I'm moving in - my only reservation is that moving to 1.0.0 implies a level of stability I'm not convinced we're at, there's also the fact that this library can't read things like CIF files which are valid STAR files. This is because they contain multiple "blocks" under the same data label, something I didn't have in mind when writing this and which broke my mental model of the parsing flow

**Comment by Guillawme** [comment]
Then I think a compatibility-breaking change is fine either way: [according to SemVer, any version pre-1.0.0 means the interface is not stable](https://semver.org/#spec-item-4) and may change between any minor or patch number change.

**Comment by alisterburt** [comment]
closed by #10 - thanks for your feedback @Guillawme and @robertbuecker 

updated to v0.4.0 - all tests are passing but please do let me know if you find any teething problems, updated details in the readme! I hope I didn't break too many of your scripts :octopus:

**Comment by Guillawme** [comment]
Accessing by column name instead of index will make my scripts more robust, certainly won't break them once I migrate from column index to column name. Thank you!

There's a little typo in the README under the "Testing" section: the link to pytest points to gemmi.

**Comment by alisterburt** [comment]
Thanks for catching that! Fixed
